// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDangKySuDungPhongMay.Models;

#nullable disable

namespace WebDangKySuDungPhongMay.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240606055726_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.Admin", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TenHienThi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TenDangNhap");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            TenDangNhap = "admin",
                            MatKhau = "123456789",
                            TenHienThi = "Quản lý"
                        });
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.GiangVien", b =>
                {
                    b.Property<string>("MaGiangVien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaGiangVien");

                    b.ToTable("GiangViens");

                    b.HasData(
                        new
                        {
                            MaGiangVien = "GV001",
                            Email = "nguyenvana@ute.edu.vn",
                            GioiTinh = "Nam",
                            HoTen = "Nguyễn Văn A",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456789",
                            TrangThai = true
                        },
                        new
                        {
                            MaGiangVien = "GV002",
                            Email = "tranthib@ute.edu.vn",
                            GioiTinh = "Nữ",
                            HoTen = "Trần Thị B",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0987654321",
                            TrangThai = true
                        },
                        new
                        {
                            MaGiangVien = "GV003",
                            Email = "lethic@ute.edu.vn",
                            GioiTinh = "Nữ",
                            HoTen = "Lê Thị C",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(1978, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0912345678",
                            TrangThai = true
                        },
                        new
                        {
                            MaGiangVien = "GV004",
                            Email = "phamvand@ute.edu.vn",
                            GioiTinh = "Nam",
                            HoTen = "Phạm Văn D",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(1990, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0908765432",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.HocKy", b =>
                {
                    b.Property<int>("MaHocKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocKy"));

                    b.Property<string>("TenHocKy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHocKy");

                    b.ToTable("HocKys");

                    b.HasData(
                        new
                        {
                            MaHocKy = 1,
                            TenHocKy = "1"
                        },
                        new
                        {
                            MaHocKy = 2,
                            TenHocKy = "2"
                        },
                        new
                        {
                            MaHocKy = 3,
                            TenHocKy = "Hè"
                        });
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.LopHocPhan", b =>
                {
                    b.Property<string>("MaLopHocPhan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaHocKy")
                        .HasColumnType("int");

                    b.Property<string>("MaMonHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaNamHoc")
                        .HasColumnType("int");

                    b.Property<int>("SoSinhVienToiDa")
                        .HasColumnType("int");

                    b.HasKey("MaLopHocPhan");

                    b.HasIndex("MaHocKy");

                    b.HasIndex("MaMonHoc");

                    b.HasIndex("MaNamHoc");

                    b.ToTable("LopHocPhans");

                    b.HasData(
                        new
                        {
                            MaLopHocPhan = "LHP001",
                            MaHocKy = 1,
                            MaMonHoc = "TOEN430979",
                            MaNamHoc = 1,
                            SoSinhVienToiDa = 30
                        },
                        new
                        {
                            MaLopHocPhan = "LHP002",
                            MaHocKy = 1,
                            MaMonHoc = "SOPM431679",
                            MaNamHoc = 1,
                            SoSinhVienToiDa = 25
                        },
                        new
                        {
                            MaLopHocPhan = "LHP003",
                            MaHocKy = 2,
                            MaMonHoc = "ADMP431879",
                            MaNamHoc = 1,
                            SoSinhVienToiDa = 20
                        },
                        new
                        {
                            MaLopHocPhan = "LHP004",
                            MaHocKy = 2,
                            MaMonHoc = "ADPL331379",
                            MaNamHoc = 2,
                            SoSinhVienToiDa = 35
                        });
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.MayTinh", b =>
                {
                    b.Property<string>("MaMay")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TinhTrangMayTinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("bit");

                    b.HasKey("MaMay");

                    b.HasIndex("MaPhong");

                    b.ToTable("MayTinhs");

                    b.HasData(
                        new
                        {
                            MaMay = "MT001",
                            MaPhong = "PM001",
                            TinhTrangMayTinh = "Hoạt động tốt",
                            TrangThai = true
                        },
                        new
                        {
                            MaMay = "MT002",
                            MaPhong = "PM002",
                            TinhTrangMayTinh = "Đang bảo trì",
                            TrangThai = false
                        },
                        new
                        {
                            MaMay = "MT003",
                            MaPhong = "PM003",
                            TinhTrangMayTinh = "Hoạt động tốt",
                            TrangThai = true
                        },
                        new
                        {
                            MaMay = "MT004",
                            MaPhong = "PM004",
                            TinhTrangMayTinh = "Đang bảo trì",
                            TrangThai = false
                        });
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.MonHoc", b =>
                {
                    b.Property<string>("MaMonHoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TinChiLyThuyet")
                        .HasColumnType("int");

                    b.Property<int>("TinChiThucHanh")
                        .HasColumnType("int");

                    b.HasKey("MaMonHoc");

                    b.ToTable("MonHocs");

                    b.HasData(
                        new
                        {
                            MaMonHoc = "TOEN430979",
                            TenMonHoc = "Công cụ và môi trường phát triển PM",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "SOPM431679",
                            TenMonHoc = "Quản lý dự án phần mềm",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "ADMP431879",
                            TenMonHoc = "Lập trình di động nâng cao",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "ADPL331379",
                            TenMonHoc = "Ngôn ngữ Lập trình tiên tiến",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "DIFO432180",
                            TenMonHoc = "Pháp lý kỹ thuật số",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "WISE432380",
                            TenMonHoc = "An toàn mạng không dây và di động",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "BCAP433280",
                            TenMonHoc = "Blockchain và ứng dụng",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "CLAD432480",
                            TenMonHoc = "Quản trị trên môi trường cloud",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "ADDB331784",
                            TenMonHoc = "Cơ sở dữ liệu Nâng cao",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "DAWH430784",
                            TenMonHoc = "Kho dữ liệu",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "INRE431084",
                            TenMonHoc = "Truy tìm thông tin",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "SEEN431579",
                            TenMonHoc = "Search Engine",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "AIOT331185",
                            TenMonHoc = "Trí tuệ nhân tạo cho IOT",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "PCOM331285",
                            TenMonHoc = "Tính toán song song",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "NLPR431585",
                            TenMonHoc = "Xử lý ngôn ngữ tự nhiên",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "RELE431685",
                            TenMonHoc = "Học tăng cường",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "WESE331479",
                            TenMonHoc = "Bảo mật web",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "OOSD330879",
                            TenMonHoc = "Thiết kế phần mềm hướng đối tượng",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "MOPR331279",
                            TenMonHoc = "Lập trình di động",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "SOTE431079",
                            TenMonHoc = "Kiểm thử phần mềm",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "MTSE431179",
                            TenMonHoc = "Các công nghệ phần mềm mới",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "POSE451479",
                            TenMonHoc = "Tiểu luận chuyên ngành CNPM",
                            TinChiLyThuyet = 5,
                            TinChiThucHanh = 0
                        },
                        new
                        {
                            MaMonHoc = "NPRO430980",
                            TenMonHoc = "Lập trình mạng",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "ADNT330580",
                            TenMonHoc = "Mạng máy tính nâng cao",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "ETHA332080",
                            TenMonHoc = "Tấn công mạng và phòng thủ",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "CNDE430780",
                            TenMonHoc = "Thiết kế mạng",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "NSEC430880",
                            TenMonHoc = "An ninh mạng",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "POCN451280",
                            TenMonHoc = "Tiểu luận chuyên ngành Mạng và an ninh mạng",
                            TinChiLyThuyet = 5,
                            TinChiThucHanh = 0
                        },
                        new
                        {
                            MaMonHoc = "ISAD330384",
                            TenMonHoc = "Phân tích và thiết kế hệ thống thông tin",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        },
                        new
                        {
                            MaMonHoc = "DAMI330484",
                            TenMonHoc = "Khai phá dữ liệu",
                            TinChiLyThuyet = 2,
                            TinChiThucHanh = 1
                        });
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.NamHoc", b =>
                {
                    b.Property<int>("MaNamHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNamHoc"));

                    b.Property<int>("NamBatDau")
                        .HasColumnType("int");

                    b.Property<int>("NamKetThuc")
                        .HasColumnType("int");

                    b.HasKey("MaNamHoc");

                    b.ToTable("NamHocs");

                    b.HasData(
                        new
                        {
                            MaNamHoc = 1,
                            NamBatDau = 2022,
                            NamKetThuc = 2023
                        },
                        new
                        {
                            MaNamHoc = 2,
                            NamBatDau = 2023,
                            NamKetThuc = 2024
                        },
                        new
                        {
                            MaNamHoc = 3,
                            NamBatDau = 2024,
                            NamKetThuc = 2025
                        });
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.NguoiQuanLyPhongMay", b =>
                {
                    b.Property<string>("MaNguoiQuanLy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNguoiQuanLy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaNguoiQuanLy");

                    b.ToTable("NguoiQuanLyPhongMays");

                    b.HasData(
                        new
                        {
                            MaNguoiQuanLy = "NQL001",
                            Email = "nguyenvanq@ute.edu.vn",
                            GioiTinh = "Nam",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456789",
                            TenNguoiQuanLy = "Nguyễn Văn Q",
                            TrangThai = true
                        },
                        new
                        {
                            MaNguoiQuanLy = "NQL002",
                            Email = "tranthip@ute.edu.vn",
                            GioiTinh = "Nữ",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0987654321",
                            TenNguoiQuanLy = "Trần Thị P",
                            TrangThai = true
                        },
                        new
                        {
                            MaNguoiQuanLy = "NQL003",
                            Email = "lethir@ute.edu.vn",
                            GioiTinh = "Nữ",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(1978, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0912345678",
                            TenNguoiQuanLy = "Lê Thị R",
                            TrangThai = true
                        },
                        new
                        {
                            MaNguoiQuanLy = "NQL004",
                            Email = "phamvans@ute.edu.vn",
                            GioiTinh = "Nam",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(1990, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0908765432",
                            TenNguoiQuanLy = "Phạm Văn S",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.PhieuDangKyGV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MaGiangVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaLopHocPhan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaPhongMay")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgaySuDung")
                        .HasColumnType("date");

                    b.Property<int>("TietBatDau")
                        .HasColumnType("int");

                    b.Property<int>("TietKetThuc")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaLopHocPhan");

                    b.HasIndex("MaPhongMay");

                    b.ToTable("PhieuDangKyGVs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GhiChu = "Không có",
                            LyDo = "Sử dụng phòng máy cho lớp học",
                            MaGiangVien = "GV001",
                            MaLopHocPhan = "LHP001",
                            MaPhongMay = "PM001",
                            NgayDangKy = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySuDung = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TietBatDau = 1,
                            TietKetThuc = 3,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 2,
                            GhiChu = "Không có",
                            LyDo = "Sử dụng phòng máy cho nghiên cứu",
                            MaGiangVien = "GV002",
                            MaLopHocPhan = "LHP002",
                            MaPhongMay = "PM002",
                            NgayDangKy = new DateTime(2023, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySuDung = new DateTime(2023, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TietBatDau = 4,
                            TietKetThuc = 6,
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.PhieuDangKySV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaPhongMay")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgaySuDung")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("ThoiGianBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("ThoiGianKetThuc")
                        .HasColumnType("time");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MaPhongMay");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("PhieuDangKySVs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GhiChu = "Mang theo laptop",
                            LyDo = "Làm bài tập nhóm",
                            MaPhongMay = "PM001",
                            MaSinhVien = "16110250",
                            NgayDangKy = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySuDung = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianBatDau = new TimeSpan(0, 9, 0, 0, 0),
                            ThoiGianKetThuc = new TimeSpan(0, 11, 0, 0, 0),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 2,
                            GhiChu = "Mang theo tài liệu",
                            LyDo = "Nghiên cứu dự án",
                            MaPhongMay = "PM002",
                            MaSinhVien = "16110052",
                            NgayDangKy = new DateTime(2024, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySuDung = new DateTime(2024, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianBatDau = new TimeSpan(0, 13, 0, 0, 0),
                            ThoiGianKetThuc = new TimeSpan(0, 15, 0, 0, 0),
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.PhongMay", b =>
                {
                    b.Property<string>("MaPhongMay")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaNguoiQuanLy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TinhTrangPhongMay")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaPhongMay");

                    b.HasIndex("MaNguoiQuanLy");

                    b.ToTable("PhongMays");

                    b.HasData(
                        new
                        {
                            MaPhongMay = "PM001",
                            MaNguoiQuanLy = "NQL001",
                            TinhTrangPhongMay = "Hoạt động tốt",
                            TrangThai = true
                        },
                        new
                        {
                            MaPhongMay = "PM002",
                            MaNguoiQuanLy = "NQL002",
                            TinhTrangPhongMay = "Đang bảo trì",
                            TrangThai = false
                        },
                        new
                        {
                            MaPhongMay = "PM003",
                            MaNguoiQuanLy = "NQL003",
                            TinhTrangPhongMay = "Hoạt động tốt",
                            TrangThai = true
                        },
                        new
                        {
                            MaPhongMay = "PM004",
                            MaNguoiQuanLy = "NQL004",
                            TinhTrangPhongMay = "Đang bảo trì",
                            TrangThai = false
                        });
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSinhVien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenSinhVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaSinhVien");

                    b.ToTable("SinhViens");

                    b.HasData(
                        new
                        {
                            MaSinhVien = "16110250",
                            Email = "16110250@ute.edu.vn",
                            GioiTinh = "Nam",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2000, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456789",
                            TenSinhVien = "Nguyễn Hoàng Thanh Tùng",
                            TrangThai = true
                        },
                        new
                        {
                            MaSinhVien = "16110052",
                            Email = "16110052@ute.edu.vn",
                            GioiTinh = "Nam",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2000, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456790",
                            TenSinhVien = "Vũ Tấn Đạt",
                            TrangThai = true
                        },
                        new
                        {
                            MaSinhVien = "16110195",
                            Email = "16110195@ute.edu.vn",
                            GioiTinh = "Nam",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2000, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456791",
                            TenSinhVien = "Nguyễn Ngọc Quý",
                            TrangThai = true
                        },
                        new
                        {
                            MaSinhVien = "16110236",
                            Email = "16110236@ute.edu.vn",
                            GioiTinh = "Nam",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2000, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456792",
                            TenSinhVien = "Võ Châu Nhật Trường",
                            TrangThai = true
                        },
                        new
                        {
                            MaSinhVien = "17116192",
                            Email = "17116192@ute.edu.vn",
                            GioiTinh = "Nữ",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456780",
                            TenSinhVien = "Trần Kim Ngân",
                            TrangThai = true
                        },
                        new
                        {
                            MaSinhVien = "17116145",
                            Email = "17116145@ute.edu.vn",
                            GioiTinh = "Nam",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2000, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456781",
                            TenSinhVien = "Lê Nguyễn Phúc Vĩnh",
                            TrangThai = true
                        },
                        new
                        {
                            MaSinhVien = "18116141",
                            Email = "18116141@ute.edu.vn",
                            GioiTinh = "Nữ",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2000, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456782",
                            TenSinhVien = "Nguyễn Lê Diễm Tú",
                            TrangThai = true
                        },
                        new
                        {
                            MaSinhVien = "18116095",
                            Email = "18116095@ute.edu.vn",
                            GioiTinh = "Nam",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2000, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456783",
                            TenSinhVien = "Lê Đại Nghĩa",
                            TrangThai = true
                        },
                        new
                        {
                            MaSinhVien = "18116069",
                            Email = "18116069@ute.edu.vn",
                            GioiTinh = "Nam",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2000, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456784",
                            TenSinhVien = "Phạm Gia Huy",
                            TrangThai = true
                        },
                        new
                        {
                            MaSinhVien = "19116164",
                            Email = "19116164@ute.edu.vn",
                            GioiTinh = "Nữ",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2000, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456785",
                            TenSinhVien = "Nguyễn Thị Xuân Đào",
                            TrangThai = true
                        },
                        new
                        {
                            MaSinhVien = "19116162",
                            Email = "19116162@ute.edu.vn",
                            GioiTinh = "Nữ",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2000, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456786",
                            TenSinhVien = "Trương Thị Thùy Dương",
                            TrangThai = true
                        },
                        new
                        {
                            MaSinhVien = "19116165",
                            Email = "19116165@ute.edu.vn",
                            GioiTinh = "Nam",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2000, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456787",
                            TenSinhVien = "Vũ Trọng Đạt",
                            TrangThai = true
                        },
                        new
                        {
                            MaSinhVien = "19116227",
                            Email = "19116227@ute.edu.vn",
                            GioiTinh = "Nữ",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2000, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456788",
                            TenSinhVien = "Nguyễn Ngọc Quế Trân",
                            TrangThai = true
                        },
                        new
                        {
                            MaSinhVien = "19116237",
                            Email = "19116237@ute.edu.vn",
                            GioiTinh = "Nữ",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2000, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456789",
                            TenSinhVien = "Lê Hà Hoàng Yến",
                            TrangThai = true
                        },
                        new
                        {
                            MaSinhVien = "19116207",
                            Email = "19116207@ute.edu.vn",
                            GioiTinh = "Nam",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2000, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456790",
                            TenSinhVien = "Bùi Nhật Phúc",
                            TrangThai = true
                        },
                        new
                        {
                            MaSinhVien = "19116185",
                            Email = "19116185@ute.edu.vn",
                            GioiTinh = "Nữ",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2000, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456791",
                            TenSinhVien = "Tiêu Kim Loan",
                            TrangThai = true
                        },
                        new
                        {
                            MaSinhVien = "19116196",
                            Email = "19116196@ute.edu.vn",
                            GioiTinh = "Nữ",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456792",
                            TenSinhVien = "Nguyễn Thị Thanh Nhàn",
                            TrangThai = true
                        },
                        new
                        {
                            MaSinhVien = "19116026",
                            Email = "19116026@ute.edu.vn",
                            GioiTinh = "Nữ",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2001, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456793",
                            TenSinhVien = "Nguyễn Thụy Quế Ngân",
                            TrangThai = true
                        },
                        new
                        {
                            MaSinhVien = "19116231",
                            Email = "19116231@ute.edu.vn",
                            GioiTinh = "Nữ",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2001, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456794",
                            TenSinhVien = "Nguyễn Phương Uyên",
                            TrangThai = true
                        },
                        new
                        {
                            MaSinhVien = "19116230",
                            Email = "19116230@ute.edu.vn",
                            GioiTinh = "Nữ",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2001, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456795",
                            TenSinhVien = "Huỳnh Thị Bích Tuyền",
                            TrangThai = true
                        },
                        new
                        {
                            MaSinhVien = "19116190",
                            Email = "19116190@ute.edu.vn",
                            GioiTinh = "Nữ",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2001, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456796",
                            TenSinhVien = "Nguyễn Thị Na",
                            TrangThai = true
                        },
                        new
                        {
                            MaSinhVien = "19116232",
                            Email = "19116232@ute.edu.vn",
                            GioiTinh = "Nữ",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2001, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456797",
                            TenSinhVien = "Lê Thị Thúy Uyển",
                            TrangThai = true
                        },
                        new
                        {
                            MaSinhVien = "19116157",
                            Email = "19116157@ute.edu.vn",
                            GioiTinh = "Nam",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2001, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456798",
                            TenSinhVien = "Lý Chánh Bình",
                            TrangThai = true
                        },
                        new
                        {
                            MaSinhVien = "19116215",
                            Email = "19116215@ute.edu.vn",
                            GioiTinh = "Nữ",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2001, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456799",
                            TenSinhVien = "Nguyễn Thị Hồng Thắm",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.SinhVienLopHocPhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaLopHocPhan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MaLopHocPhan");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("SinhVienLopHocPhans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaLopHocPhan = "LHP001",
                            MaSinhVien = "16110250"
                        },
                        new
                        {
                            Id = 2,
                            MaLopHocPhan = "LHP002",
                            MaSinhVien = "16110052"
                        },
                        new
                        {
                            Id = 3,
                            MaLopHocPhan = "LHP003",
                            MaSinhVien = "16110195"
                        },
                        new
                        {
                            Id = 4,
                            MaLopHocPhan = "LHP004",
                            MaSinhVien = "16110236"
                        },
                        new
                        {
                            Id = 5,
                            MaLopHocPhan = "LHP001",
                            MaSinhVien = "17116192"
                        },
                        new
                        {
                            Id = 6,
                            MaLopHocPhan = "LHP002",
                            MaSinhVien = "17116145"
                        },
                        new
                        {
                            Id = 7,
                            MaLopHocPhan = "LHP003",
                            MaSinhVien = "18116141"
                        },
                        new
                        {
                            Id = 8,
                            MaLopHocPhan = "LHP004",
                            MaSinhVien = "18116095"
                        },
                        new
                        {
                            Id = 9,
                            MaLopHocPhan = "LHP001",
                            MaSinhVien = "18116069"
                        },
                        new
                        {
                            Id = 10,
                            MaLopHocPhan = "LHP002",
                            MaSinhVien = "19116164"
                        },
                        new
                        {
                            Id = 11,
                            MaLopHocPhan = "LHP003",
                            MaSinhVien = "19116162"
                        },
                        new
                        {
                            Id = 12,
                            MaLopHocPhan = "LHP004",
                            MaSinhVien = "19116165"
                        },
                        new
                        {
                            Id = 13,
                            MaLopHocPhan = "LHP001",
                            MaSinhVien = "19116227"
                        },
                        new
                        {
                            Id = 14,
                            MaLopHocPhan = "LHP002",
                            MaSinhVien = "19116237"
                        },
                        new
                        {
                            Id = 15,
                            MaLopHocPhan = "LHP003",
                            MaSinhVien = "19116207"
                        },
                        new
                        {
                            Id = 16,
                            MaLopHocPhan = "LHP004",
                            MaSinhVien = "19116185"
                        },
                        new
                        {
                            Id = 17,
                            MaLopHocPhan = "LHP001",
                            MaSinhVien = "19116196"
                        },
                        new
                        {
                            Id = 18,
                            MaLopHocPhan = "LHP002",
                            MaSinhVien = "19116026"
                        },
                        new
                        {
                            Id = 19,
                            MaLopHocPhan = "LHP003",
                            MaSinhVien = "19116231"
                        },
                        new
                        {
                            Id = 20,
                            MaLopHocPhan = "LHP004",
                            MaSinhVien = "19116230"
                        });
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<string>("MaNguoiQuanLy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<DateTime>("ThoiGianDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaThongBao");

                    b.HasIndex("MaNguoiQuanLy");

                    b.ToTable("ThongBaos");

                    b.HasData(
                        new
                        {
                            MaThongBao = 1,
                            MaNguoiQuanLy = "NQL001",
                            NoiDung = "<p>Phòng máy PM001 sẽ được bảo trì vào ngày 10/07/2023.</p>",
                            ThoiGianDang = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TieuDe = "Thông báo bảo trì phòng máy"
                        },
                        new
                        {
                            MaThongBao = 2,
                            MaNguoiQuanLy = "NQL002",
                            NoiDung = "<p>Lịch học kỳ mới đã được cập nhật trên hệ thống. Vui lòng kiểm tra chi tiết.</p>",
                            ThoiGianDang = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TieuDe = "Thông báo lịch học kỳ mới"
                        },
                        new
                        {
                            MaThongBao = 3,
                            MaNguoiQuanLy = "NQL003",
                            NoiDung = "<p>Kỳ thi giữa kỳ sẽ diễn ra từ ngày 20/07/2023 đến 30/07/2023.</p>",
                            ThoiGianDang = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TieuDe = "Thông báo thi giữa kỳ"
                        },
                        new
                        {
                            MaThongBao = 4,
                            MaNguoiQuanLy = "NQL004",
                            NoiDung = "<p>Hội thảo về công nghệ mới sẽ được tổ chức vào ngày 25/07/2023 tại hội trường lớn.</p>",
                            ThoiGianDang = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TieuDe = "Thông báo hội thảo công nghệ"
                        });
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.LopHocPhan", b =>
                {
                    b.HasOne("WebDangKySuDungPhongMay.Models.HocKy", "HocKy")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("MaHocKy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebDangKySuDungPhongMay.Models.MonHoc", "MonHoc")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebDangKySuDungPhongMay.Models.NamHoc", "NamHoc")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("MaNamHoc")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HocKy");

                    b.Navigation("MonHoc");

                    b.Navigation("NamHoc");
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.MayTinh", b =>
                {
                    b.HasOne("WebDangKySuDungPhongMay.Models.PhongMay", "PhongMay")
                        .WithMany("MayTinhs")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhongMay");
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.PhieuDangKyGV", b =>
                {
                    b.HasOne("WebDangKySuDungPhongMay.Models.GiangVien", "GiangVien")
                        .WithMany("PhieuDangKyGVs")
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebDangKySuDungPhongMay.Models.LopHocPhan", "LopHocPhan")
                        .WithMany("PhieuDangKyGVs")
                        .HasForeignKey("MaLopHocPhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebDangKySuDungPhongMay.Models.PhongMay", "PhongMay")
                        .WithMany("PhieuDangKyGVs")
                        .HasForeignKey("MaPhongMay")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("LopHocPhan");

                    b.Navigation("PhongMay");
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.PhieuDangKySV", b =>
                {
                    b.HasOne("WebDangKySuDungPhongMay.Models.PhongMay", "PhongMay")
                        .WithMany("PhieuDangKySVs")
                        .HasForeignKey("MaPhongMay")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebDangKySuDungPhongMay.Models.SinhVien", "SinhVien")
                        .WithMany("PhieuDangKySVs")
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhongMay");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.PhongMay", b =>
                {
                    b.HasOne("WebDangKySuDungPhongMay.Models.NguoiQuanLyPhongMay", "NguoiQuanLyPhongMay")
                        .WithMany("PhongMays")
                        .HasForeignKey("MaNguoiQuanLy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NguoiQuanLyPhongMay");
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.SinhVienLopHocPhan", b =>
                {
                    b.HasOne("WebDangKySuDungPhongMay.Models.LopHocPhan", "LopHocPhan")
                        .WithMany("SinhVienLopHocPhans")
                        .HasForeignKey("MaLopHocPhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebDangKySuDungPhongMay.Models.SinhVien", "SinhVien")
                        .WithMany("SinhVienLopHocPhans")
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHocPhan");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.ThongBao", b =>
                {
                    b.HasOne("WebDangKySuDungPhongMay.Models.NguoiQuanLyPhongMay", "NguoiQuanLyPhongMay")
                        .WithMany("ThongBaos")
                        .HasForeignKey("MaNguoiQuanLy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiQuanLyPhongMay");
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.GiangVien", b =>
                {
                    b.Navigation("PhieuDangKyGVs");
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.HocKy", b =>
                {
                    b.Navigation("LopHocPhans");
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.LopHocPhan", b =>
                {
                    b.Navigation("PhieuDangKyGVs");

                    b.Navigation("SinhVienLopHocPhans");
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.MonHoc", b =>
                {
                    b.Navigation("LopHocPhans");
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.NamHoc", b =>
                {
                    b.Navigation("LopHocPhans");
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.NguoiQuanLyPhongMay", b =>
                {
                    b.Navigation("PhongMays");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.PhongMay", b =>
                {
                    b.Navigation("MayTinhs");

                    b.Navigation("PhieuDangKyGVs");

                    b.Navigation("PhieuDangKySVs");
                });

            modelBuilder.Entity("WebDangKySuDungPhongMay.Models.SinhVien", b =>
                {
                    b.Navigation("PhieuDangKySVs");

                    b.Navigation("SinhVienLopHocPhans");
                });
#pragma warning restore 612, 618
        }
    }
}
